services:
  - type: web
    name: linkisend-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    rootDir: backend
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
